import Navbar from "./layouts/navbar/navbar";
import {Inter} from "next/font/google";
import "./globals.css"

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={` ${inter.variable}`}>
      <Navbar/>
        <div>{children}</div>
        
      </body>
    </html>
  );
}
